// Portfolio routes + navigation smoke test. BASE=https://eric-bridoux.vercel.app node tools/portfolio-e2e.mjs
import { chromium } from 'playwright-core'
const b = await chromium.launch({ channel: 'msedge' })
const p = await b.newPage({ viewport: { width: 1440, height: 900 } })
const errors = []
p.on('pageerror', (e) => errors.push(String(e)))
p.on('console', (m) => m.type() === 'error' && errors.push(m.text()))
const BASE = process.env.BASE ?? 'http://localhost:5100'
const out = []
const check = (n, ok, x = '') => out.push(`${ok ? 'PASS' : 'FAIL'}  ${n}${x ? '  — ' + x : ''}`)

await p.goto(BASE + '/', { waitUntil: 'networkidle' })
await p.waitForTimeout(3600)
check('home: no switcher', (await p.locator('.props').count()) === 0)
check('home: 5 project rows', (await p.locator('.ca-row').count()) === 5)
check('home: title', (await p.title()).includes('Custom websites'), await p.title())
check('home: concept work label', (await p.locator('.ca-toolbar__count').textContent()).startsWith('Concept work'))
await p.evaluate(() => document.querySelector('#work').scrollIntoView())
await p.waitForTimeout(1500)
await p.locator('.ca-row a').nth(2).click()
await p.waitForTimeout(2500)
check('row → case study URL', p.url().endsWith('/work/kestrel'), p.url())
check('case study: title', (await p.locator('.cs-title').textContent()).includes('Kestrel Orbital'))
check('case study: live link', (await p.locator('.cs-live').getAttribute('href')) === 'https://kestrel-orbital.vercel.app')
await p.screenshot({ path: 'shots/cs-kestrel-top.png' })
await p.locator('.cs-next').click()
await p.waitForTimeout(2000)
check('next project → togen', p.url().endsWith('/work/togen'), p.url())
await p.goBack()
await p.waitForTimeout(1500)
check('back button → kestrel', p.url().endsWith('/work/kestrel'), p.url())
await p.locator('.cs-back').click()
await p.waitForTimeout(2500)
check('← Index returns home', new URL(p.url()).pathname === '/', p.url())
check('loader skipped on return', !(await p.locator('.ca-loader').isVisible().catch(() => false)))
for (const [path, sel] of [['/exhibition', '.cb-hero'], ['/live', '.cc-hero']]) {
  await p.goto(BASE + path, { waitUntil: 'networkidle' })
  await p.waitForTimeout(1500)
  check(`${path} renders standalone`, await p.locator(sel).isVisible())
}
// Services + contact form
await p.goto(BASE + '/', { waitUntil: 'load' })
await p.waitForTimeout(800)
check('services: 3 packages', (await p.locator('.ca-package').count()) === 3)
check('services: prices shown', (await p.locator('.ca-package__price b').first().textContent()).startsWith('$'))
await p.evaluate(() => document.querySelector('#services').scrollIntoView())
await p.waitForTimeout(800)
await p.locator('.ca-package__cta').nth(1).click()
await p.waitForTimeout(1500)
check('package CTA preselects service', (await p.locator('.ca-choice label.is-on').first().textContent()).trim() === 'Business site')
await p.locator('.ca-submit').click()
check('empty submit shows errors', (await p.locator('.ca-field__err').count()) === 3)
check('first invalid field focused', await p.evaluate(() => document.activeElement?.id === 'cf-name'))
await p.fill('#cf-name', 'Test Person')
await p.fill('#cf-email', 'not-an-email')
await p.fill('#cf-message', 'We are opening a bakery in spring.')
await p.locator('.ca-submit').click()
check('bad email rejected', (await p.locator('#cf-email-err').count()) === 1 && (await p.locator('.ca-field__err').count()) === 1)
await p.fill('#cf-email', 'test@studio.example')
await p.locator('.ca-submit').click()
await p.waitForTimeout(800)
const note = await p.locator('.ca-form__note').textContent()
const usesEndpoint = await p.locator('.ca-form--done').count()
check('valid submit: mailto fallback or sent', note.includes('mail app') || usesEndpoint === 1, note)
check('no console errors', errors.length === 0, errors.slice(0, 3).join(' | '))
console.log(out.join('\n'))
await b.close()
